name:                nifti-hs
version:             0.1.0.0
github:              "githubuser/nifti-hs"
license:             BSD3
author:              "Samuel Remedios, einargs"
maintainer:          "sam.remedios@gmail.com"
copyright:           "2019 S. W. Remedios, einargs"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/nifti-hs#readme>

dependencies:
- base >= 4.7 && < 5
- binary              # used in parsing
- bytestring          # used in parsing
- text                # used in parsing

library:
  source-dirs: src

executables:
  nifti-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nifti-hs

tests:
  nifti-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nifti-hs
